enableImmutableInstalls: false
enableStrictSsl: false
enableInlineBuilds: true
npmRegistryServer: "https://registry.npmjs.org"
enableTelemetry: false
enableScripts: true
yarnPath: ""
packageExtensions:
  "portfolio_nextjs@*":
    dependencies:
      react-is: "^18.2.0"